"""schema iniziale: ingredienti, ricette, dosaggi, estensione pgvector

Revision ID: 2d335d05d18c
Revises:
Create Date: 2026-09-14 17:39:41.738574

L'estensione `vector` va abilitata **prima** di creare la tabella
`ingredients`: l'immagine pgvector/pgvector rende l'estensione
disponibile sul server, ma non la attiva sul singolo database, e senza
`CREATE EXTENSION` il tipo `vector(32)` non esiste ancora quando la
colonna lo richiede.

L'indice HNSW sul profilo organolettico e' creato qui, con la tabella
vuota, perche' e' il momento in cui costa meno: su una tabella popolata
la stessa operazione richiede una scansione completa. E' dimensionato per
la distanza coseno, che e' la metrica con cui il matcher confronta i
profili (la magnitudine del vettore dipende da quanti descrittori sono
stati compilati, non da quanto gli ingredienti si somiglino).

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d335d05d18c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingredients",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "SPIRIT",
                "LIQUEUR",
                "FORTIFIED_WINE",
                "WINE",
                "BITTER",
                "AMARO",
                "JUICE",
                "SYRUP",
                "ACID_SOLUTION",
                "MIXER",
                "WATER",
                "OTHER",
                name="ingredientcategory",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("density_g_ml", sa.Float(), nullable=False),
        sa.Column("brix", sa.Float(), nullable=False),
        sa.Column("acidity", sa.Float(), nullable=False),
        sa.Column("abv", sa.Float(), nullable=False),
        sa.Column("flavor_vector", pgvector.sqlalchemy.vector.VECTOR(dim=32), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("abv >= 0 AND abv <= 1", name="ck_ingredients_abv_fraction"),
        sa.CheckConstraint("acidity >= 0 AND acidity <= 10", name="ck_ingredients_acidity_range"),
        sa.CheckConstraint("brix >= 0 AND brix <= 100", name="ck_ingredients_brix_range"),
        sa.CheckConstraint(
            "density_g_ml >= 0.7 AND density_g_ml <= 1.6", name="ck_ingredients_density_range"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_ingredients_name"),
    )
    op.create_index(
        "ix_ingredients_category_active", "ingredients", ["category", "is_active"], unique=False
    )
    op.create_table(
        "recipes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "dilution_method",
            sa.Enum(
                "SHAKEN", "STIRRED", "BUILT", name="dilutionmethod", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recipes_name"), "recipes", ["name"], unique=False)
    op.create_table(
        "recipe_ingredients",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("recipe_id", sa.String(length=36), nullable=False),
        sa.Column("ingredient_id", sa.String(length=36), nullable=False),
        sa.Column("volume_ml", sa.Float(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint("volume_ml > 0", name="ck_recipe_ingredients_positive_volume"),
        sa.ForeignKeyConstraint(["ingredient_id"], ["ingredients.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("recipe_id", "ingredient_id", name="uq_recipe_ingredient"),
    )
    op.create_index(
        "ix_recipe_ingredients_recipe", "recipe_ingredients", ["recipe_id"], unique=False
    )
    # ### end Alembic commands ###

    op.execute(
        """
        CREATE INDEX ix_ingredients_flavor_vector_hnsw
        ON ingredients
        USING hnsw (flavor_vector vector_cosine_ops)
        """
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_ingredients_flavor_vector_hnsw")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_recipe_ingredients_recipe", table_name="recipe_ingredients")
    op.drop_table("recipe_ingredients")
    op.drop_index(op.f("ix_recipes_name"), table_name="recipes")
    op.drop_table("recipes")
    op.drop_index("ix_ingredients_category_active", table_name="ingredients")
    op.drop_table("ingredients")
    # ### end Alembic commands ###

    # L'estensione si rimuove solo dopo la tabella che la usa. Il database
    # e' dedicato a questa applicazione, quindi la rimozione e' sicura e
    # rende la migrazione davvero reversibile.
    op.execute("DROP EXTENSION IF EXISTS vector")
